### ISSUE TITLE
Overlay on selection

### ISSUE THREAD

**Issue by roife** [wolray/symbol-overlay#104]
Thank you for developing this plugin. The plugin is very useful, especially the functionality of 'temp-symbol.'

However, I would like to know if it's possible to highlight only the selected area when a user chooses a certain region, for example:

![image](https://github.com/wolray/symbol-overlay/assets/17700217/cf38b865-3e64-4946-9343-fe4213f83d62)

Of course, this only affects 'temp-symbol' and doesn't impact other functionalities.

**Comment by roife** [comment]
Actually, I've already implemented this feature. I just wanted to know if this functionality would be accepted by upstream (for example, by setting an option to allow this behavior).

If possible, I'd be happy to submit my code.

**Comment by purcell** [comment]
I expect that would be out of scope for `symbol-overlay`, because it only ever highlights full symbols. IIRC, changes to highlight arbitrary strings have been declined in the past.

**Comment by purcell** [comment]
Which is to say: highlighting the region automatically would be controversial, because I imagine it immediately wouldn't work with the navigation commands, and such a thing could be trivially built if highlighting arbitrary strings were supported. Given the lack of support for merging the latter, special-case handling of the former is not likely to be merged.
