### ISSUE TITLE
symbol-overlay-mode

### ISSUE THREAD

**Issue by dakra** [wolray/symbol-overlay#2]
Hi, I like the package, especially since highlight-symbol doesn't seem to be maintained anymore.

I always use `highlight-symbol-mode` which is a minor mode that always
highlights automatically the symbol under the cursor.

Would be a nice feature for symbol-overlay as well.

Also how comes o and u are default bindings for next and prev?
Would have expected either n/p or maybe f/b.

Thanks :)

**Comment by wolray** [comment]
I use "o/u" as the common next-and-prev-like bindings when searching or moving over texts because they are at the most natural positions on the keyboard. It's comfortable for my fingers: "u/o" to move around while "i" for confirming/toggling and "k" for killing/deleting.

However, It's just a matter of personal taste. You can customize the keymap as you like.

`highlight-symbol-mode` is indeed a nice feature though I had hardly used it. Maybe it will be added to `symbol-overlay` in the future versions.

Thanks.








You can customize the keymap as you like.

**Comment by borgnix** [comment]
please add this feature :)

**Comment by dakra** [comment]
@borgnix Until this get's implemented here I have the following in my config:

**Comment by borgnix** [comment]
@dakra Thank you!

**Comment by wolray** [comment]
Good news!  We have `symbol-overlay-mode` now.

Check the new feature  after Melpa finish this build. Wish you enjoy it.

@borgnix @dakra

**Comment by dakra** [comment]
Very nice :)

I see the mode does not have a keymap and if I call
`symbol-overlay-jump-next` it says 'Symbol is not highlighted'.

I would like to bind `M-n` and `M-p` in a `symbol-overlay-mode-map` so
I can easily jump between the highlighted symbols.

Thanks :)

**Comment by wolray** [comment]
You can easily define a `symbol-overlay-mode-map` in your own init.el. And it will automatically linked to the minor-mode. Or why not just simply global-set the key?

The `user-error` of  'Symbol is not highlighted' is deleted, now you can start a jump from any position even inside a not-highlighted symbol. Same to all the other symbol-overlay commands.

For some reasons, scope is not supported in `symbol-overlay-mode`. If you wanna toggle the scope, use `symbol-overlay-put` to highlight it first.

**Comment by wolray** [comment]
Alright, you can set `symbol-overlay-temp-in-scope` to be non-nil to make `symbol-overlay-mode` highlighting in scope by default, and toggle its value anywhere outside the package.

**Comment by dakra** [comment]
Awesome.

I tried to set the minor-mode-map in use-package but that
didn't really work.
Anyway, using a global key is probably a good idea anyway.

One more thing, I saw you added `symbol-overlay-switch-forward/backward`
which I like very much and would rather use those
than `symbol-overlay-jump-next`.. but those functions
are not yet supported in the minor-mode ("No more forward symbols").

Good job :+1:

**Comment by wolray** [comment]
`switch-forward/backward` is for jumping from one symbol to another one. It doesn't make sense to support it in the minor mode, since the symbol at point is already highlighted. 

The best philosophy about symbol-overlay is to use `jump` for jumping between occurrences of a specific symbol, and `switch` for finding and switching to a new one.  As for the minor-mode, just treat it as a sort of quick preview. 

:)

**Comment by dakra** [comment]
The thing is that I want one single keybinding.
So I guess I want a `symbol-overlay-jump-next-dwim` then,
that, if `symbol-overlay-minor-mode` is active AND a symbol is
under `(point)` I want to call `jump-next` else do `switch-forward`.

Does this make sense?

Anyway, this is obviously only a very minor thing.
Closing the issue already since it works pretty much like I want now :)
