### ISSUE TITLE
sh-mode problem

### ISSUE THREAD

**Issue by luixiao1223** [wolray/symbol-overlay#21]
The behavior of symbol-overlay is not right in sh-mode.I cannot jump from a variable like "$sample" to "$sample/$somethingelse".

**Comment by purcell** [comment]
With the point in the `sample` portion of `$sample/$somethingelse`, `(thing-at-point 'symbol)` returns `sample/`. This tells me that the syntax table for `sh-mode` is unusual, and `symbol-overlay` relies on this. It's therefore not practical to fix it from this side, sorry. I guess that the syntax class of `/` is marked as "symbol" so that file paths in general are considered symbols: this would be a choice of the `sh-mode` developers, and indeed `symbol-overlay` *can* be used to jump between occurrences of `/this/path`.
