### ISSUE TITLE
[Request] highlight TODO

### ISSUE THREAD

**Issue by seagle0128** [wolray/symbol-overlay#39]
I am happy with `symbol-overlay` and [hl-todo](https://github.com/tarsius/hl-todo). But `hl-todo` uses `font-lock` while not `overlay`, so it is slow. Can you please integrate these functionalities into `symbol-overlay`? I think only highlight the keywords in comments for `prog-mode`, and all for `text-mode`. Thank you!

**Comment by purcell** [comment]
This is out of scope for `symbol-overlay`, I think.

A better approach would be to tackle any slowness in `hl-todo`: `font-lock` should not normally be slow.

Using overlays would not be ideal for this problem because they must be programmatically updated every time the text in the buffer changes (just in case new keywords need to be highlighted), and this would also get very slow.

**Comment by seagle0128** [comment]
Okay. It makes sense.
