### ISSUE TITLE
highlighting error

### ISSUE THREAD

**Issue by stardiviner** [wolray/symbol-overlay#4]
When I execute command `symbol-overlay-put` command, get this error:

```
Debugger entered--Lisp error: (wrong-type-argument number-or-marker-p nil)
  symbol-overlay-count("\\_<report\\_>" "salmon")
  symbol-overlay-put()
  funcall-interactively(symbol-overlay-put)
  call-interactively(symbol-overlay-put nil nil)
  command-execute(symbol-overlay-put)
```

**Comment by wolray** [comment]
Well, a `number-or-marker-p` error means the bug is in the function `symbol-overlay-count`. It is usually because the overlays have already changed while the buffer fails to update in time. You can try highlight another symbol elsewhere and then use `symbol-overlay-remove-all` to clear all then re-highlight the original one.

Don't worry, a new auto-refresh mechanism will be enabled in the package soon, and this error shall not happen any more then. I will inform you once the new version is released.

Thanks for your downloading.

**Comment by stardiviner** [comment]
Thanks for your new feature and quick response.

**Comment by wolray** [comment]
The source is updated now. 

 You may download the newest version of `symbol-overlay` after Melpa's next build.

Have fun!
