### ISSUE TITLE
Don't highlight symbols that appear in strings

### ISSUE THREAD

**Issue by langston-barrett** [wolray/symbol-overlay#46]
Mostly, these are just "coincidental", and don't need to be brought to the user's attention. Most major modes highlight string literals, so there should be some way to detect and avoid them.

**Comment by purcell** [comment]
The expression `(nth 3 (syntax-ppss))` returns non-`nil` when point is inside a string, so this would be easy enough to do. I tend to agree when viewing this simplistically, but there's a compelling counterpoint: inside strings in Ruby and other languages, you can interpolate code, e.g. `"hello #{name}"`. And when point is inside the interpolated code, e.g. on `name`, then `(nth 3 (syntax-ppss))` still returns non-`nil`. It's pretty clear to me that a user would still want `name` to be highlighted here.

**Comment by siddharthist** [comment]
@purcell thanks for the quick response!  You're totally right about languages like Python and Ruby with that style of format string. What about a toggle (with the default being the current behavior)? One could then enable or disable it in a major mode hook or similar.

**Comment by Hi-Angel** [comment]
Please, if you decide to address it, either leave it opt-in, or make such behavior very explicit in readme.md. People expect this mode would highlight anything that  is under the caret, and if it doesn't, this looks like a bug. In fact, [there's an actual bug](https://github.com/wolray/symbol-overlay/issues/43) where the mode doesn't highlight words sometimes.

**Comment by purcell** [comment]
My preference overall is to not add any new logic relating to this. It would be hard to implement in a sensible way. e.g. what happens if "highlighting in strings" is disabled, but a user actively tries to highlight a specific word in a string. Should that be a no-op?

In theory it looks like you could already easily get this effect on a mode-by-mode basis by adding your own function into `symbol-overlay-ignore-functions`: see [here](https://github.com/wolray/symbol-overlay/blob/8b8888c8b209effe12e7c32f65124236d7722d62/symbol-overlay.el#L159).
