### ISSUE TITLE
Highlight only variables that are in scope

### ISSUE THREAD

**Issue by dakra** [wolray/symbol-overlay#5]
It would be nice to have something like [this](http://mihai.bazon.net/projects/editing-javascript-with-emacs-js2-mode/js2-highlight-vars-mode)
but a bit more generic so someone can write "modules" for different languages so it's not only js2-mode specific.

This should probably be an extra function, so someone could highlight all words anywhere
(via regex) like now or highlight only in the current scope.
Imho, it would be really useful for refactoring.

I see that it's quite different from what symbol-overlay internally does now,
you can close this issue if you feel this is out of the scope of this package.

**Comment by wolray** [comment]
Yes, I will try.

**Comment by dakra** [comment]
Not sure if it's helpful but multiple-cursors has
a function `mc/mark-all-like-this-in-defun` and
that basically just calls `narrow-to-defun` before calling
it's own function. Maybe that's a nice and easy way
for symbol-overlay as well.

**Comment by wolray** [comment]
You are right, `narrow-to-defun` is indeed a common method for operations inside a scope. It is also used in `highlight-symbol` and will be my first choice.

**Comment by wolray** [comment]
The latest release now enables highlighting variables only in scope. It works well in lisp or python, but not in javascript, because `narrow-to-defun` doesn't know how to narrow to a specific region in such a language.

This can be handled by introducing a new buffer-local variable for users to customize.

Can you write a function that could return the beginning and end of a javascript scope, then I will be able to test this new feature for that language.

**Comment by wolray** [comment]
You may like to configure `symbol-overlay-narrow-function` to enable in-scope highlight in some languages like JS. See more detail in the documentation. @dakra 

Have fun. :)

**Comment by dakra** [comment]
Very nice. Thanks.
Maybe it makes sense to be able to specify `symbol-overlay-narrow-function` per major-mode?

Good job!

**Comment by wolray** [comment]
Of course. Just put the specification into a major-mode-hook.
